# Generated by Django 5.2.4 on 2025-08-02 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Authorization", "0003_remove_aiinteraction_prompt_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
    ]
