# Generated by Django 5.2.4 on 2025-08-06 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Topic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfavorite",
            name="topic",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="Topic.topic"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userfavorite",
            name="note",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Topic.note",
            ),
        ),
    ]
