# Generated by Django 5.2.4 on 2025-08-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Topic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="quiz_topic",
            field=models.CharField(max_length=254),
        ),
    ]
