# Generated by Django 5.2.4 on 2025-08-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Topic', '0002_userfavorite_topic_alter_userfavorite_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
