# Generated by Django 5.2.4 on 2025-08-07 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Topic", "0006_remove_chat_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="note",
        ),
        migrations.AddField(
            model_name="chat",
            name="Topic",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="Topic.topic"
            ),
            preserve_default=False,
        ),
    ]
