# Generated by Django 5.2.4 on 2025-08-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Topic", "0007_remove_chat_note_chat_topic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="Topic",
            new_name="topic",
        ),
    ]
