# Generated by Django 5.2.4 on 2025-08-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Topic", "0008_rename_topic_chat_topic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topic",
            old_name="option_a",
            new_name="option_A",
        ),
        migrations.RenameField(
            model_name="topic",
            old_name="option_b",
            new_name="option_B",
        ),
        migrations.RenameField(
            model_name="topic",
            old_name="option_c",
            new_name="option_C",
        ),
        migrations.RenameField(
            model_name="topic",
            old_name="option_d",
            new_name="option_D",
        ),
    ]
