# Generated by Django 5.2.4 on 2025-08-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Topic", "0009_rename_option_a_topic_option_a_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="difficultylevels",
            name="level_name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
