# Generated by Django 5.2.4 on 2025-08-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Topic", "0010_alter_difficultylevels_level_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
