# Generated by Django 5.2.4 on 2025-08-09 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Topic", "0011_note_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Topic.topic",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
