# Generated by Django 5.2.4 on 2025-08-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Topic', '0012_note_topic_alter_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='explanation_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
